name: Website
on:
  push:
    branches: [ master ]
    paths:
      - client/**/*
jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        name: "deploy website"
        env:
          PROJECT_ID: mm-sandbox-wasm-on-gcp
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        with:
          args: rsync -r $GITHUB_WORKSPACE/client gs://mm-sandbox-wasm-on-gcp
          cli: gsutil